"""add agent_type to agents

Revision ID: 08b3c86a657e
Revises: ed88cc6cd705
Create Date: 2026-05-06 13:12:08.898134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b3c86a657e'
down_revision: Union[str, Sequence[str], None] = 'ed88cc6cd705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agent_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'agent_type')
    # ### end Alembic commands ###
