"""add provider and model to agents

Revision ID: 32994866f4f0
Revises: 464097d46823
Create Date: 2026-05-06 11:05:24.796604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32994866f4f0'
down_revision: Union[str, Sequence[str], None] = '464097d46823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'model')
    op.drop_column('agents', 'provider')
    # ### end Alembic commands ###
