"""add callback_url to runs

Revision ID: 464097d46823
Revises: 0c6f1cdf9d4b
Create Date: 2026-05-06 01:39:55.020072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464097d46823'
down_revision: Union[str, Sequence[str], None] = '0c6f1cdf9d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('callback_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'callback_url')
    # ### end Alembic commands ###
