"""add users table and user_id to agents and runs

Revision ID: 71a9bb70bac9
Revises: 32994866f4f0
Create Date: 2026-05-06 11:30:20.951008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a9bb70bac9'
down_revision: Union[str, Sequence[str], None] = '32994866f4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('runs', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'user_id')
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###
