"""add task_prompt to runs

Revision ID: ff53edc81bc4
Revises: 08b3c86a657e
Create Date: 2026-05-06 13:59:07.616965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff53edc81bc4'
down_revision: Union[str, Sequence[str], None] = '08b3c86a657e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('task_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'task_prompt')
    # ### end Alembic commands ###
